V 1.4.0 1rc
medcomdk/dk-medcom-terminology pull request #17
Opened 2023-05-23 12:04 UTC by mbumedcom

Jeg har tilføjet fejlkoder som jeg tænker er relevante for FHIR meddelelser. jeg har både taget nogen fra valuesettet fra FHIR og selv defineret par stykker

2023-05-25 12:34 UTC, ovi-medcom requested changes
have left my further comments in a mail. /Ole

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* $AckOperationOutcomeCodes#MSG_DUBLICATE_ID "Duplicate Id %s for resource type %s"
"MSG_DUBLICATE_ID" should be "MSG_DUPLICATE_ID"

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* $AckOperationOutcomeCodes#MSG_NO_MATCH "No Resource found matchning the query"
"matchning" should be "matching"

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* $AckOperationOutcomeCodes#MSG_NO_EXIST "Resource Id  dose not exist"
"Resource Id  dose not exist" should be "Resource Id does not exist"

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* $AckOperationOutcomeCodes#MSG_NO_MODULE "No module could be found to handle the request"
What does this mean?

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* $AckOperationOutcomeCodes#MSG_TRANSACTION_DUBLICATE_ID "Dublicate Identifier in transaction: %s"
"Dublicate" should be "Duplicate"

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* $AckOperationOutcomeCodes#MSG_UNKNOWN_OPERATION "Unknown FHIR http operation"
Should this be present, there's no http communication going on.

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
> +* #MSG_Receiver_Identifier_UNKNIWN "Receiver identifier unknown" from system medcom-acknowledgement-error-codes
"MSG_Receiver_Identifier_UNKNIWN" should be "MSG_Receiver_Identifier_UNKNOWN"

2023-05-25 12:34 UTC, ovi-medcom commented on input/fsh/MedComCorePractitionerRolesAutorisationsregistret.fsh
>  * #socialogsundhedsassistent "Social-og- sundhedsassistent"
"Social-og- sundhedsassistent" should be "Social- og sundhedsassistent"

2023-06-29 09:32 UTC, tmsMedcom commented on input/fsh/MedComAcknowledgementErrorCodes.fsh
Linje 4 - 'descriptions' i stedet for 'describtions' og uden mellemrum til sidst
linje 7 - date skal opdateres

2023-06-29 09:34 UTC, tmsMedcom commented on input/fsh/MedComAcknowledgementIssueDetails.fsh
linje 17 - fjern '-a.1' fra versionsnummeret
linje 18 - draft skal ændres til active.
linje 19 - opdater dato

2023-06-29 09:37 UTC, tmsMedcom commented
Jeg har lige tilføjet nogle kommentarer til versionsnumre, dato og lignende. Jeg antager, at koderne er reviewet af @ovi-medcom.

2023-06-29 09:39 UTC, mbumedcom commented
Yes jeg kigger på kommentarerne efter frokost 😊

Mvh
Marta Burek
________________________________
Fra: tmsMedcom ***@***.***>
Sendt: Thursday, June 29, 2023 11:37:38 AM
Til: medcomdk/dk-medcom-terminology ***@***.***>
Cc: Marta Burek ***@***.***>; Author ***@***.***>
Emne: Re: [medcomdk/dk-medcom-terminology] V 1.4.0 1rc (PR #17)


Jeg har lige tilføjet nogle kommentarer til versionsnumre, dato og lignende. Jeg antager, at koderne er reviewet af @ovi-medcom<https://github.com/ovi-medcom>.

—
Reply to this email directly, view it on GitHub<https://github.com/medcomdk/dk-medcom-terminology/pull/17#issuecomment-1612716036>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZTM4QBFPZQIGVR6CO4GWIDXNVEGFANCNFSM6AAAAAAYLZEEGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-29 10:33 UTC, mbumedcom commented
Så har jeg implementeret rettelserne 😊


Venlig hilsen

Marta Burek
Standardiseringskonsulent
MedCom, Forskerparken 10, 5230 Odense M
Mobi: (+45) 29 10 17 76
***@***.******@***.***>
[Et billede, der indeholder tekst, knojern, clipart, gear  Automatisk genereret beskrivelse]

Fra: tmsMedcom ***@***.***>
Sendt: 29. juni 2023 11:38
Til: medcomdk/dk-medcom-terminology ***@***.***>
Cc: Marta Burek ***@***.***>; Author ***@***.***>
Emne: Re: [medcomdk/dk-medcom-terminology] V 1.4.0 1rc (PR #17)


Jeg har lige tilføjet nogle kommentarer til versionsnumre, dato og lignende. Jeg antager, at koderne er reviewet af @ovi-medcom<https://github.com/ovi-medcom>.

—
Reply to this email directly, view it on GitHub<https://github.com/medcomdk/dk-medcom-terminology/pull/17#issuecomment-1612716036>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZTM4QBFPZQIGVR6CO4GWIDXNVEGFANCNFSM6AAAAAAYLZEEGU>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-06-29 12:41 UTC, tmsMedcom commented
@ovi-medcom er kodene for [input/fsh/MedComAcknowledgementIssueDetails.fsh](https://github.com/medcomdk/dk-medcom-terminology/pull/17/files/a9f7a5fa1ff5b189a79a68189266fedca585cbc6#diff-ea433f4458668e349ab5277b20fb61494410a1566b9445aeda1d4ee63189b03e) ok til publicering?

2023-06-29 13:11 UTC, ovi-medcom commented on input/fsh/MedComCorePractitionerRolesAutorisationsregistret.fsh
>  * #radiograf "Radiofraf"
radiograf!

2023-07-10 12:17 UTC, merged